-keep class com.allmightgamebooster.gusdev.xposed.ModuleMain { *; }
-keep class * implements de.robv.android.xposed.IXposedHookLoadPackage { *; }
-keep class * implements de.robv.android.xposed.IXposedHookZygoteInit { *; }
-keepattributes *Annotation*
